### ISSUE TITLE
Allow giving "forbidden" regexes names

### ISSUE THREAD

**Issue by jonas-schievink** [jonas-schievink/cargo-tidy#2]
This can possibly make some config file self-explanatory and allows reporting better errors.

Example:

```toml
[forbidden-content]
no-windows-or-osx-line-breaks = "\\r"
no-tabs = "\\t"
no-trailing-whitespace = " $"
```
